/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ahorcado;

import javax.swing.JOptionPane;

/*
 *
 * 
 */
public class GuiInicio extends javax.swing.JFrame {
    
    /**
     * Creates new form GuiInicio
     */
    public GuiInicio() {
        initComponents();
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabelAhorcado = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(205, 41, 8));
        jButton1.setFont(new java.awt.Font("NanumMyeongjo", 1, 15)); // NOI18N
        jButton1.setForeground(new java.awt.Color(49, 33, 28));
        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, 80, 40));

        jLabelAhorcado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Ahorcadito.png"))); // NOI18N
        getContentPane().add(jLabelAhorcado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 310, 290));

        jLabel1.setBackground(new java.awt.Color(153, 139, 125));
        jLabel1.setFont(new java.awt.Font("Courier 10 Pitch", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(87, 66, 66));
        jLabel1.setText("AHORCADONS");
        jLabel1.setDoubleBuffered(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 290, -1));

        jButton2.setBackground(new java.awt.Color(201, 13, 13));
        jButton2.setFont(new java.awt.Font("NanumMyeongjo", 1, 15)); // NOI18N
        jButton2.setForeground(new java.awt.Color(30, 16, 16));
        jButton2.setText("AcercaDe");
        jButton2.setToolTipText("");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 120, 40));

        jLabel2.setBackground(new java.awt.Color(242, 236, 229));
        jLabel2.setForeground(new java.awt.Color(237, 227, 227));
        jLabel2.setText("Version 1.0 Dons.INCORPORATION");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, -1, -1));

        jButton3.setBackground(new java.awt.Color(154, 128, 137));
        jButton3.setFont(new java.awt.Font("NanumMyeongjo", 1, 15)); // NOI18N
        jButton3.setText("Inicio");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 120, 210, 60));

        jButton4.setBackground(new java.awt.Color(154, 128, 137));
        jButton4.setFont(new java.awt.Font("NanumMyeongjo", 1, 15)); // NOI18N
        jButton4.setText("Como se juega");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, 210, 60));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Reserbado.jpg"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //Boton Salir
        GUIGracias g = new GUIGracias();
        g.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        //Inicio del JUego
        GUITipoJuego b = new GUITipoJuego();
        b.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
      //Como se JUega
        GuiComosejuega a=new GuiComosejuega();
      a.setVisible(true);
      this.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //Acerca DE
        String Info=".\nEste juego fue creado en el 2017 con la colaboracion de los Developers\n"
                + "   ---->Juan Hernandez Montalvo\n"
                + "   ---->Juan Antoio Ovalle Patiño\n"
                + "   ---->Raul Ortega Avila\n"
                + "   ---->Luis ALejandro Hinojosa Peres\n"
                + "Muchas Gracias por escoger nuestros juegos de la industria\n"
                + "   ---->Dons.Incorporation\nCualquier duda o aclaracion contacte con los telefonos\n"
                + "tel:4921353270 ó 4921320546\n"
                + "Correo: jhernandezmontalvo@gmail.com\n";
        String nombre=JOptionPane.showInputDialog(null,"Cual es tu Nombre ahorcadonito: ","AhorcaDons",JOptionPane.INFORMATION_MESSAGE);
        JOptionPane.showMessageDialog(null,"Hola "+nombre+" "+Info,"AhorcaDOns",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiInicio().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelAhorcado;
    private javax.swing.JLabel jLabelFondo;
    // End of variables declaration//GEN-END:variables
}
