/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ahorcado;
import javax.swing.JOptionPane;
/**
 *
 * 
 */
public class GUITipoJuego extends javax.swing.JFrame {
    DosJugadores d = new DosJugadores();
    /**
     * Creates new form GUITipoJuego
     */
    public GUITipoJuego() {
        initComponents();
        this.setLocationRelativeTo(null);
        d = new DosJugadores();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Salir = new javax.swing.JButton();
        Regresar = new javax.swing.JButton();
        UJ = new javax.swing.JButton();
        DJ = new javax.swing.JButton();
        UJ2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelAhorcado = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Salir.setBackground(new java.awt.Color(205, 41, 8));
        Salir.setFont(new java.awt.Font("NanumMyeongjo", 1, 15)); // NOI18N
        Salir.setForeground(new java.awt.Color(49, 33, 28));
        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        getContentPane().add(Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, 80, 40));

        Regresar.setBackground(new java.awt.Color(201, 13, 13));
        Regresar.setFont(new java.awt.Font("NanumMyeongjo", 1, 15)); // NOI18N
        Regresar.setForeground(new java.awt.Color(41, 41, 41));
        Regresar.setText("Regresar");
        Regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresarActionPerformed(evt);
            }
        });
        getContentPane().add(Regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, 100, 30));

        UJ.setBackground(new java.awt.Color(154, 128, 137));
        UJ.setFont(new java.awt.Font("NanumMyeongjo", 1, 15)); // NOI18N
        UJ.setText("Un Jugador");
        UJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UJActionPerformed(evt);
            }
        });
        getContentPane().add(UJ, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, 140, 40));

        DJ.setBackground(new java.awt.Color(154, 128, 137));
        DJ.setFont(new java.awt.Font("NanumMyeongjo", 1, 15)); // NOI18N
        DJ.setText("Dos Jugadores");
        DJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DJActionPerformed(evt);
            }
        });
        getContentPane().add(DJ, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 180, 140, 40));

        UJ2.setBackground(new java.awt.Color(154, 128, 137));
        UJ2.setFont(new java.awt.Font("NanumMyeongjo", 1, 15)); // NOI18N
        UJ2.setText("Un Jugador");
        UJ2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UJ2ActionPerformed(evt);
            }
        });
        getContentPane().add(UJ2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 280, 140, 40));

        jLabel1.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel1.setText("Tipo de juego:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, -1, -1));

        jLabel3.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel3.setText("Con tiempo:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, -1, -1));

        jLabelAhorcado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Ahorcadito.png"))); // NOI18N
        getContentPane().add(jLabelAhorcado, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 310, 290));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Reserbado.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 391));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DJActionPerformed
        GUIVentanaJuego2 v = new GUIVentanaJuego2();
        v.setVisible(true);
        this.setVisible(false);
        JOptionPane.showMessageDialog(null,"Poner la plabra en el espacio segun \na quien le toque y presionar en guardar"
                + "\nSolo poner letras","AhorcaDons",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_DJActionPerformed

    private void RegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresarActionPerformed
        // Regresar al inicio.
        GuiInicio a=new GuiInicio();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_RegresarActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        // TODO add your handling code here:
        GUIGracias g = new GUIGracias();
        g.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_SalirActionPerformed

    private void UJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UJActionPerformed
        // TODO add your handling code here:
        GUiVentanaJuego b=new GUiVentanaJuego();
        b.setVisible(true);
        this.setVisible(false);
        JOptionPane.showMessageDialog(null,"Selecciona el tipo de la palabra que deceas adivinar"
                + "\nen la esquina superior izquierda","AhorcaDons",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_UJActionPerformed

    private void UJ2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UJ2ActionPerformed
        // TODO add your handling code here:
        GUIVentanaJuego3 v = new GUIVentanaJuego3();
        v.setVisible(true);
        this.setVisible(false);
        JOptionPane.showMessageDialog(null,"Selecciona el tipo de la palabra que deceas adivinar"
                + "\nen la esquina superior izquierda","AhorcaDons",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_UJ2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUITipoJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUITipoJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUITipoJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUITipoJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUITipoJuego().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DJ;
    private javax.swing.JButton Regresar;
    private javax.swing.JButton Salir;
    private javax.swing.JButton UJ;
    private javax.swing.JButton UJ2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelAhorcado;
    // End of variables declaration//GEN-END:variables
}
